app = "exitlag-free"
primary_region = "gru"

[build]

[env]
  DEBUG = "False"
  ALLOWED_HOST = "exitlag-free.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"
  protocol = "http"
  timeout = "2s"
  tls_skip_verify = false

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 800

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512